#! /bin/bash

export VERSION="50"
export SYSTEM_DESC="ChimeraOS"
export SYSTEM_NAME="chimeraos"
export USERNAME="gamer"
export SIZE="20000MB"
export ARCHIVE_DATE=$(date -d 'yesterday' +%Y/%m/%d)
export WEBSITE="https://chimeraos.org"
export DOCUMENTATION_URL="https://chimeraos.org/about"
export BUG_REPORT_URL="https://github.com/ChimeraOS/chimeraos/issues"

export KERNEL_PACKAGE="linux-skchos"
export KERNEL_PACKAGE_ORIGIN="local"

export PACKAGES="\
	accountsservice \
	acpi_call-dkms \
	alsa-firmware \
	alsa-utils \
	amd-ucode \
	bash-completion \
	broadcom-wl-dkms \
	bzip2 \
	cifs-utils \
	cpupower \
	diffutils \
	dkms \
	distrobox \
	dmidecode \
	efibootmgr \
	evtest \
	fakeroot \
	ffmpeg \
	file \
	ffmpegthumbnailer \
	firejail \
	flatpak \
	fmt \
	fuse-zip \
	fuse2 \
	fwupd \
	git \
	gst-plugin-pipewire \
	gvfs-smb \
	gvfs-nfs \
	gzip \
	htop \
	intel-gpu-tools \
	intel-media-driver \
	intel-ucode \
	intel-undervolt \
	less \
	lib32-curl \
	lib32-fontconfig \
	lib32-freetype2 \
	lib32-libgpg-error \
	lib32-libnm \
	lib32-libxinerama \
	lib32-libxcrypt-compat \
	lib32-mangohud \
	lib32-openal \
	lib32-pipewire \
	lib32-systemd \
	lib32-vulkan-icd-loader \
	libcurl-gnutls \
	libidn11 \
	libxcrypt-compat \
	libxss \
	lightdm \
	linux-firmware \
	liquidctl \
	logrotate \
	lrzip \
	lshw \
	mesa-demos \
	modemmanager \
	nano \
	networkmanager \
	nfs-utils \
	noto-fonts-emoji \
	nss-mdns \
	openal \
	openssh \
	p7zip \
	pipewire \
	pipewire-alsa \
	pipewire-jack \
	pipewire-pulse \
	podman \
	pulsemixer \
	python \
	qtractor \
	rsync \
	smbclient \
	sof-firmware \
	sshfs \
	steam \
	sudo \
	tar \
	tree \
	ttf-liberation \
	unace \
	unrar \
	unzip \
	usb_modeswitch \
	usbutils \
	vim \
	vulkan-icd-loader \
	wavpack \
	wget \
	which \
	wireplumber \
	wqy-microhei \
	xdg-desktop-portal \
	xdg-desktop-portal-wlr \
	xf86-video-amdgpu \
	xorg-server \
	xz \
	zip \
"

export PACKAGE_OVERRIDES="\
	https://github.com/3003n/linux-chimeraos/releases/download/v6.14.6-8/linux-skchos-6.14.6-8-x86_64.pkg.tar.zst \
	https://github.com/3003n/linux-chimeraos/releases/download/v6.14.6-8/linux-skchos-headers-6.14.6-8-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-git-packages/releases/download/aae67ab/lib32-mesa-git-25.2.0_devel.206177.aae67ab678a.869876d-1-x86_64.pkg.tar.zst \
	https://github.com/3003n/mesa-git-packages/releases/download/aae67ab/mesa-git-25.2.0_devel.206177.aae67ab678a.869876d-1-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/packages/l/libibus/libibus-1.5.30-3-x86_64.pkg.tar.zst \
	https://archive.archlinux.org/packages/i/ibus/ibus-1.5.30-3-x86_64.pkg.tar.zst \
	https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/ibus-pinyin-1.5.1-2.2-x86_64.pkg.tar.zst \
"

# Each entry is the clone url (https://aur.archlinux.org/{AUR_PACKAGE}.git)
# Which is often the same as the package name but it can be different.
# Check on the AUR webpage if you are unsure
export AUR_PACKAGES="\
	ayaneo-platform-dkms-git \
	ayn-platform-dkms-git \
	bcm20702a1-firmware \
	chimeraos-device-quirks-sk-git \
	downgrade \
	evdev-keepalive \
	frzr-sk \
	gamescope-session-sk-git \
	gamescope-session-steam-plus-git \
	gamescope-sk \
	gpd-fan-driver-dkms-git \
	gpdconfig-git \
	hhd \
	hhd-ui \
	hhfc-git \
	hid-msi-claw-dkms-git \
	inputplumber-bin \
	kanit-font \
	linux-firmware-valve \
	nintendo-udev \
	pikaur \
	rtl8812au-dkms-git \
	rtl8814au-dkms-git \
	rtl8821au-dkms-git \
	ryzenadj-git \
	sk-boot-to-windows \
	sk-chos-tool \
	steam_notif_daemon \
	steam-powerbuttond-git \
	v4l-utils-git \
	waydroid-script-git \
	yay-git \
	zenergy-dkms-git \
"

export PACKAGES_TO_DELETE="\
	amdvlk \
	clang \
	jack2 \
	lib32-amdvlk \
	lib32-clang \
	openvr \
	pulseaudio \
	pulseaudio-alsa \
	v4l-utils \
"
export OWN_PACKAGES_FILE_TO_DELETE="\
	*gamescope-3.1*.pkg.tar.zst \
"

export AUR_PACKAGES_FILE_TO_DELETE="\
	*gamescope-session-git-r*.pkg.tar.zst \
	*gamescope-3.1*.pkg.tar.zst \
"

export SERVICES="\
	NetworkManager \
	avahi-daemon \
	auto-expand-home \
	bluetooth \
	bluetooth-workaround \
	cec-onboot \
	cec-onpoweroff \
	cec-onsleep \
	fstrim.timer \
	frzr_root-swap-swapfile.swap \
	haveged \
	hostname-fix \
	inputplumber \
	inputplumber-suspend \
	lightdm \
	overlay-backgrounds \
	overlay-fonts \
	overlay-root-home \
	powerstation \
	scx_loader \
	steam-powerbuttond \
	steamos-manager \
	sshd \
	systemd-timesyncd \
	swapfile \
	sk-bind-mount \
	sk-chos-daemon \
	sk-chos-tool-autoupdate.timer \
	sk-setup-kernel-options \
	sk-resume \
"

export USER_SERVICES="\
	pipewire \
	podman \
	sk-chos-user-daemon \
	sk-first-setup-daemon \
	sk-audio-setup \
	monitor-waydroid \
"

export FILES_TO_DELETE="\
	/boot/initramfs-linux-fallback.img \
	/usr/share/SFML \
	/usr/share/doc \
	/usr/share/gtk-doc \
	/usr/share/help \
	/usr/share/man \
	/usr/share/libalpm/hooks/70-dkms-install.hook \
	/usr/share/libalpm/hooks/70-dkms-upgrade.hook \
	/usr/share/libalpm/hooks/71-dkms-remove.hook \
"

postinstallhook() {
	# Add sudo permissions

	sed -i "s/Defaults secure_path=/# Defaults secure_path=/g" /etc/sudoers

	# sk chimeraos
	sed -i 's/set mouse=a/set mouse-=a/g' /usr/share/vim/vim*/defaults.vim
	ln -s -f /usr/bin/vim /usr/bin/vi
	sed -i "s/PasswordAuthentication no/PasswordAuthentication yes/" /etc/ssh/sshd_config
	sed -i "s/#SuspendEstimationSec=60min/SuspendEstimationSec=30min/" /etc/systemd/sleep.conf

	# podman
	echo "unqualified-search-registries = ['docker.io']" >>/etc/containers/registries.conf

	remove_packages=(
		make
		cmake
		gcc
		ardour
		wine
		)
	for package in "${remove_packages[@]}"; do
		pacman --noconfirm -Rnsdd "$package" || true
	done

	# clean up desktop shortcuts
	sed -i -e 's/Name=Steam (Runtime)/Name=Steam/' /usr/share/applications/steam.desktop

	sed -i 's,Exec=/usr/bin/steam-runtime,Exec=/usr/bin/chimera-steam,' /usr/share/applications/steam.desktop
	sed -i 's,Exec=/usr/bin/steam,Exec=/usr/bin/chimera-steam,' /usr/share/applications/steam.desktop

	# Waydroid
	cp /usr/share/applications/Waydroid.desktop /usr/share/applications/Waydroid-Native.desktop
	sed -i 's/Name=Waydroid/Name=Waydroid-Native/g' /usr/share/applications/Waydroid-Native.desktop
	sed -i 's@Exec=waydroid first-launch@Exec=/usr/bin/waydroid-launcher\nX-Steam-Library-Capsule=/usr/share/applications/Waydroid/capsule.png\nX-Steam-Library-Hero=/usr/share/applications/Waydroid/hero.png\nX-Steam-Library-Logo=/usr/share/applications/Waydroid/logo.png\nX-Steam-Library-StoreCapsule=/usr/share/applications/Waydroid/store-logo.png\nX-Steam-Controller-Template=Desktop@g' /usr/share/applications/Waydroid.desktop
	curl -Lo /usr/bin/waydroid-choose-gpu https://raw.githubusercontent.com/Quackdoc/waydroid-scripts/main/waydroid-choose-gpu.sh
	chmod +x /usr/bin/waydroid-choose-gpu

	# scx-scheds
	sed -i 's/SCX_SCHEDULER=scx_bpfland/SCX_SCHEDULER=scx_lavd/g' /etc/default/scx
	sed -i "s/#SCX_FLAGS=.*/SCX_FLAGS='--autopower'/g" /etc/default/scx

	# if mutter-x11-scaling is installed, add 'x11-randr-fractional-scaling' to experimental-features
	dconf_conf_path="/etc/dconf/db/local.d/00-sk-global"
	if pacman -Q mutter-x11-scaling > /dev/null 2>&1; then
		if [ -f "$dconf_conf_path" ] && ! grep -q "x11-randr-fractional-scaling" "$dconf_conf_path"; then
			sed -i "s/experimental-features=\['/experimental-features=\['x11-randr-fractional-scaling','/g" "$dconf_conf_path"
		fi
	fi

	# set permissions for intel_gpu_top and gamescope
	setcap cap_perfmon=+ep /usr/bin/intel_gpu_top
	setcap 'CAP_SYS_NICE=eip' /usr/bin/gamescope

	setcap cap_perfmon=+ep /usr/bin/mangohud

	# Disable SPDIF/IEC958 audio output
	sudo sed -e '/\[Mapping iec958/,+5 s/^/#/' -i '/usr/share/alsa-card-profile/mixer/profile-sets/default.conf'
}
