default_sched = "scx_bpfland"
default_mode = "Auto"

[scheds.scx_lavd]
auto_mode = ["--autopower"]
gaming_mode = ["--performance"]
lowlatency_mode = ["--performance"]
powersave_mode = ["--powersave"]

[scheds.scx_bpfland]
auto_mode = ["--primary-domain", "auto", "--slice-us", "20000", "--slice-us-lag", "20000", "--idle-resume-us", "10000", "--cpufreq"]
gaming_mode = ["--primary-domain", "performance", "--slice-us", "10000", "--slice-us-min", "500", "--slice-us-lag", "30000", "--idle-resume-us", "5000", "--cpufreq", "--disable-numa"]
lowlatency_mode = ["--primary-domain", "performance", "--slice-us", "5000", "--slice-us-min", "500", "--slice-us-lag", "40000", "--idle-resume-us", "1000", "--cpufreq", "--local-kthreads"]
powersave_mode = ["--primary-domain", "powersave", "--slice-us", "30000", "--slice-us-min", "2000", "--slice-us-lag", "10000", "--idle-resume-us", "30000", "--cpufreq", "--no-preempt"]
