#! /bin/bash

export SUB_PACKAGES="\
    bluedevil \
    breeze-gtk \
    deepin-wallpapers \
    discover \
    dolphin \
    dolphin-plugins \
    falkon \
    fcitx5-im \
    fcitx5-chinese-addons \
    flatpak-kcm \
    kate \
    kde-gtk-config \
    kdeconnect \
    kdeplasma-addons \
    kfind \
    kgamma \
    kinfocenter \
    konsole \
    kpipewire \
    kscreen \
    ksshaskpass \
    kwallet-pam \
    onboard \
    partitionmanager \
    plasma-browser-integration \
    plasma-desktop \
    plasma-disks \
    plasma-nm \
    plasma-pa \
    plasma-thunderbolt \
    plasma-vault \
    python-notify2 \
    xdg-desktop-portal-gtk \
    xdg-desktop-portal-kde \
"

export SUB_AUR_PACKAGES="\
    plasma5-themes-vapor-steamos \
"

export SUB_LOCAL_PACKAGES="\
	ds-inhibit \
	lact-libadwaita \
	mangohud-git \
	msi-ec-dkms-git \
	rtl88x2bu-dkms \
	steam-removable-media-git \
	xonedo-dkms \
	xonedo-firmware \
"

sub_postinstallhook() {
    :
}