#! /bin/bash

for base in base-*; do
	source $base
done

export POSTCOPY="\
	plasma \
	skel \
	wallpapers/wallpapers \
"

export SUB_PACKAGES="\
	$BASE_KDE_PACKAGES \
	nvidia-open-dkms \
	opencl-nvidia \
	lib32-opencl-nvidia \
	nvidia-utils \
	lib32-nvidia-utils \
	nvidia-prime \
"

export SUB_AUR_PACKAGES="\
	$BASE_KDE_AUR_PACKAGES \
"

export SUB_LOCAL_PACKAGES="\
	$BASE_LOCAL_PACKAGES \
"

export SUB_PACKAGES_TO_DELETE="\
	gnome-desktop \
	mutter \
"

sub_postinstallhook() {
	sed -i 's/^/nvidia-drm.modeset=1 /' /usr/lib/frzr.d/bootconfig.conf
}