#! /bin/bash

export POSTCOPY="\
	plasma \
	skel \
	wallpapers/wallpapers \
"

export SUB_PACKAGES="\
	ark \
	bluedevil \
	breeze-gtk \
	deepin-wallpapers \
	discover \
	dolphin \
	dolphin-plugins \
	falkon \
	fcitx5-im \
	fcitx5-chinese-addons \
	flatpak-kcm \
	gwenview \
	kate \
	kde-gtk-config \
	kdeconnect \
	kdeplasma-addons \
	kfind \
	kgamma \
	kinfocenter \
	konsole \
	kpipewire \
	krdc \
	krdp \
	kscreen \
	ksshaskpass \
	kwallet-pam \
	onboard \
	partitionmanager \
	plasma-browser-integration \
	plasma-desktop \
	plasma-disks \
	plasma-nm \
	plasma-pa \
	plasma-systemmonitor \
	plasma-thunderbolt \
	plasma-vault \
	python-notify2 \
	xdg-desktop-portal-gtk \
	xdg-desktop-portal-kde \
	nvidia-open-dkms \
	opencl-nvidia \
	lib32-opencl-nvidia \
	nvidia-utils \
	lib32-nvidia-utils \
	nvidia-prime \
"

export SUB_AUR_PACKAGES="\
	plasma6-themes-vapor-steamos \
"

export SUB_LOCAL_PACKAGES="\
	ds-inhibit \
	mangohud-git \
	rtl88x2bu-dkms \
	steam-removable-media-git \
	xonedo-dkms \
	xonedo-firmware \
"

export SUB_PACKAGES_TO_DELETE="\
	gnome-desktop \
	mutter \
"

sub_postinstallhook() {
	sed -i 's/^/nvidia-drm.modeset=1 /' /usr/lib/frzr.d/bootconfig.conf
}