#! /bin/bash

for base in base-*; do
	source $base
done

export POSTCOPY="\
	gnome \
	wallpapers/gnome-backgrounds \
	wallpapers/gnome-backgrounds-cachyos \
"

export SUB_PACKAGES="\
	$BASE_GNOME_PACKAGES \
	nvidia-open-dkms \
	opencl-nvidia \
	lib32-opencl-nvidia \
	nvidia-utils \
	lib32-nvidia-utils \
	nvidia-prime \
"

export SUB_AUR_PACKAGES="\
	$BASE_GNOME_AUR_PACKAGES \
"

export SUB_LOCAL_PACKAGES="\
	$BASE_LOCAL_PACKAGES \
	gnome-shell-extension-hibernate-status-git \
	gnome-shell-extension-logo-menu \
"

export SUB_PACKAGES_TO_DELETE="\
"

sub_postinstallhook() {
	install -Dm755 -t /etc/skel/Desktop/ /usr/share/applications/{org.chimeraos.session-return,sk-chos-tool}.desktop
	# add nvidia-drm.modeset=1 to /usr/lib/frzr.d/bootconfig.conf line start
	sed -i 's/^/nvidia-drm.modeset=1 /' /usr/lib/frzr.d/bootconfig.conf
}
