#! /bin/bash

for base in base-*; do
	source $base
done

export POSTCOPY="\
	plasma \
	skel \
	wallpapers/wallpapers \
"

export SUB_PACKAGES="\
	$BASE_PACKAGES \
	$BASE_KDE_PACKAGES \
"

export SUB_AUR_PACKAGES="\
	$BASE_AUR_PACKAGES \
	$BASE_KDE_AUR_PACKAGES \
	linuxqq \
	microsoft-edge-stable-bin \
	qqmusic-bin \
"

export SUB_LOCAL_PACKAGES="\
	$BASE_LOCAL_PACKAGES \
"

export SUB_PACKAGES_TO_DELETE="\
	gnome-desktop \
	mutter \
"

export SUB_PACKAGE_OVERRIDES="\
	https://ns.switchsystem.eu.org/d/vfs/guest/stos/pkgs/cursor-extracted-1.1.6-1-x86_64.pkg.tar.zst \
"

sub_postinstallhook() {
	temp_pkg_dir=$(mktemp -d)
	wget -q $SUB_PACKAGE_OVERRIDES

	pacman --noconfirm -U --overwrite='*' temp_pkg_dir/*.pkg.tar.zst --needed
	rm -rf $temp_pkg_dir
}