#! /bin/bash

export POSTCOPY="\
	gnome \
"

export SUB_PACKAGES="\
	dconf-editor \
	epiphany \
	gnome-browser-connector \
	gnome-console \
	gnome-control-center \
	gnome-disk-utility \
	gnome-keyring \
	gnome-session \
	gnome-shell \
	gnome-software \
	gnome-system-monitor \
	gnome-text-editor \
	gnome-tweaks \
	gnome-remote-desktop \
	gnome-shell-extensions \
	gnome-shell-extension-appindicator \
	gnome-shell-extension-desktop-icons-ng \
	gnome-menus \
	loupe \
	nautilus \
	noto-fonts-cjk \
	papirus-icon-theme \
	xdg-desktop-portal-gnome \
	xdg-user-dirs-gtk \
	nvidia-open-dkms \
	opencl-nvidia \
	lib32-opencl-nvidia \
	nvidia-utils \
	lib32-nvidia-utils \
	nvidia-prime \
"

export SUB_AUR_PACKAGES="\
	gnome-shell-extension-bluetooth-battery-meter-git \
	gnome-shell-extension-blur-my-shell \
	gnome-shell-extension-dash-to-dock \
	gnome-shell-extension-enhanced-osk-git \
	gnome-shell-extension-hibernate-status-git \
	gnome-shell-extension-logo-menu \
	gnome-shell-extension-screen-autorotate \
	mutter-x11-scaling \
"

export SUB_LOCAL_PACKAGES="\
	ds-inhibit \
	mangohud-git \
	msi-ec-dkms-git \
	rtl88x2bu-dkms \
	steam-removable-media-git \
	xonedo-dkms \
	xonedo-firmware \
"

export SUB_PACKAGES_TO_DELETE="\
	mutter \
"

sub_postinstallhook() {
	# add nvidia-drm.modeset=1 to /usr/lib/frzr.d/bootconfig.conf line start
	sed -i 's/^/nvidia-drm.modeset=1 /' /usr/lib/frzr.d/bootconfig.conf
}