#! /bin/bash

export SUB_PACKAGES="\
	dconf-editor \
	epiphany \
	gnome-browser-connector \
	gnome-console \
	gnome-control-center \
	gnome-disk-utility \
	gnome-keyring \
	gnome-session \
	gnome-shell \
	gnome-software \
	gnome-system-monitor \
	gnome-text-editor \
	gnome-tweaks \
	gnome-remote-desktop \
	gnome-shell-extensions \
	gnome-shell-extension-appindicator \
	gnome-shell-extension-desktop-icons-ng \
	gnome-menus \
	loupe \
	nautilus \
	noto-fonts-cjk \
	papirus-icon-theme \
	xdg-desktop-portal-gnome \
	xdg-user-dirs-gtk \
"

export SUB_AUR_PACKAGES="\
	gnome-shell-extension-bluetooth-battery-meter-git \
	gnome-shell-extension-blur-my-shell \
	gnome-shell-extension-dash-to-dock \
	gnome-shell-extension-enhanced-osk-git \
	gnome-shell-extension-hibernate-status-git \
	gnome-shell-extension-screen-autorotate \
"

export SUB_LOCAL_PACKAGES="\
	ds-inhibit \
	gnome-shell-extension-logo-menu \
	mangohud-git \
	msi-ec-dkms-git \
	rtl88x2bu-dkms \
	steam-removable-media-git \
	xonedo-dkms \
	xonedo-firmware \
"

sub_postinstallhook() {
	:
}