name: Build ChimeraOS image matrix
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  workflow_call:
    inputs:
      postfix:
        type: string
        description: Postfix used in release.
        default: ''

jobs:
  list-branches:
    name: List branches
    runs-on: ubuntu-latest
    outputs:
      branches: ${{ steps.set-branches.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: set-branches
        # remove branch/ prefix
        run: echo "matrix=$(ls -d branch/*/ | sed 's/branch\///' | sed 's/\///' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        shell: bash
  
  build-system-image:
    needs: list-branches
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: true
      matrix:
        branch: ${{ fromJson(needs.list-branches.outputs.branches) }}
    steps:
      - uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - uses: actions/download-artifact@v4
        with:
            pattern: AUR-packages*
            merge-multiple: true
            path: aur-pkgs/
      - uses: actions/download-artifact@v4
        with:
            pattern: Packages*
            merge-multiple: true
            path: pkgs/
      - name: Pre build image
        run: |
          env BUILD_BRANCH=${{ matrix.branch }} ./pre-build-image.sh
      
      - name: Build system image
        id: build_image
        run: |
          docker pull ${{ steps.meta.outputs.tags }}
          docker run -u root --rm --entrypoint=/workdir/build-image.sh -v $(pwd):/workdir -v $(pwd)/output:/output -v $GITHUB_OUTPUT:$GITHUB_OUTPUT -e "GITHUB_OUTPUT=$GITHUB_OUTPUT" --privileged=true ${{ steps.meta.outputs.tags }} $(echo ${GITHUB_SHA} | cut -c1-7)
          echo -e "$(docker inspect --format='{{index .RepoDigests 0}}' ${{ steps.meta.outputs.tags }})" > output/container.txt
      