name: System image matrix build - stable

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - matrix*
  workflow_dispatch:

jobs:
  build-docker-image:
    name: Build and publish docker container
    # uses: ./.github/workflows/build-builder.yml
    runs-on: ubuntu-latest
    steps:
      - run: echo "skip in test"

  list-pkgbuilds:
    name: List Packages
    runs-on: ubuntu-latest
    outputs:
      aur-pkgs: ${{ steps.set-aur-pkgs.outputs.matrix }}
      pkgs: ${{ steps.set-pkgs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - id: set-aur-pkgs
        run: echo "matrix=$(ls -d aur-pkgs/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        shell: bash
      - id: set-pkgs
        run: echo "matrix=$(ls -d pkgs/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
        shell: bash

  aur-pkgbuild:
    needs:
     - build-docker-image
     - list-pkgbuilds
    name: Build AUR package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: ${{ fromJson(needs.list-pkgbuilds.outputs.aur-pkgs) }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Process package name
        id: process_package
        run: |
          PACKAGE_NAME=${{ matrix.package }}
          PACKAGE_NAME=${PACKAGE_NAME#aur-pkgs/}
          PACKAGE_NAME=${PACKAGE_NAME%/}
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Fake build
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
        run: touch aur-pkgs/${{ env.PACKAGE_NAME }}.pkg.tar

      - name: Upload Package Archives
        uses: actions/upload-artifact@v4
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
        with:
            name: AUR-packages-${{ env.PACKAGE_NAME }}
            path: |
              aur-pkgs/*.pkg.tar*
            overwrite: true
            retention-days: 3

  pkgbuild:
    needs:
     - build-docker-image
     - list-pkgbuilds
    name: Build package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: ${{ fromJson(needs.list-pkgbuilds.outputs.pkgs) }}
    steps:
      - uses: actions/checkout@v4

      - name: Process package name
        id: process_package
        run: |
          PACKAGE_NAME=${{ matrix.package }}
          PACKAGE_NAME=${PACKAGE_NAME#pkgs/}
          PACKAGE_NAME=${PACKAGE_NAME%/}
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV 
     
      - name: Fake build
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
        run: touch pkgs/${{ env.PACKAGE_NAME }}.pkg.tar

      - name: Upload Package Archives
        uses: actions/upload-artifact@v4
        env:
          PACKAGE_NAME: ${{ env.PACKAGE_NAME }}
        with:
            name: Packages-${{ env.PACKAGE_NAME }}
            path: |
              pkgs/*.pkg.tar*
            overwrite: true
            retention-days: 3

  build:
    needs:
      - build-docker-image
      - aur-pkgbuild
      - pkgbuild
    name: Build ChimeraOS STABLE image matrix
    uses: ./.github/workflows/build-system-image-matrix.yml