name: Test PAT Token

on:
  workflow_dispatch:

jobs:
  test-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test token availability
        run: |
          echo "Testing PAT_SK_API_INFO token..."
          if [ -n "${{ secrets.PAT_SK_API_INFO }}" ]; then
            echo "✅ Token exists and has content"
            echo "Token length: ${#PAT_TOKEN}"
          else
            echo "❌ Token is empty or does not exist"
            exit 1
          fi
        env:
          PAT_TOKEN: ${{ secrets.PAT_SK_API_INFO }}
      
      - name: Test GitHub API access
        run: |
          echo "Testing GitHub API access..."
          curl -H "Authorization: Bearer ${{ secrets.PAT_SK_API_INFO }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/user
      
      - name: Test repository access
        run: |
          echo "Testing repository access..."
          curl -H "Authorization: Bearer ${{ secrets.PAT_SK_API_INFO }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}
      
      - name: Test create release (dry run)
        id: test_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.PAT_SK_API_INFO }}
          tag_name: test-tag-${{ github.run_number }}
          name: Test Release ${{ github.run_number }}
          draft: true
          prerelease: true
          body: |
            This is a test release to verify PAT_SK_API_INFO token.
            This release will be deleted after testing.
      
      - name: Delete test release
        if: steps.test_release.outputs.id
        run: |
          echo "Deleting test release..."
          curl -X DELETE \
               -H "Authorization: Bearer ${{ secrets.PAT_SK_API_INFO }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/releases/${{ steps.test_release.outputs.id }}
          
          echo "Deleting test tag..."
          curl -X DELETE \
               -H "Authorization: Bearer ${{ secrets.PAT_SK_API_INFO }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/git/refs/tags/test-tag-${{ github.run_number }}
      
      - name: Test result
        run: |
          echo "🎉 All tests passed! PAT_SK_API_INFO token is working correctly."
